import os

class Constants:
    SCREEN_WIDTH = 700
    SCREEN_HEIGHT = 700
    BLACK = (0, 0, 0)
    RED = (255, 0, 0)
    GREEN = (0, 255, 0)
    BLUE = (0, 0, 255)
    WAITING_SCREEN_BACKGROUND = os.path.abspath('./images/waiting-scene.jpg')
    PLAYING_SCREEN_BACKGROUND = os.path.abspath('./images/playing-scene1.jpg')
    WIN_BACKGROUND_IMAGE = os.path.abspath('images/win.jpg')
    LOSE_BACKGROUND_IMAGE = os.path.abspath('images/lost2.png')
    ROCK_BUTTON_IMAGE = os.path.abspath('./images/rock.png')
    PAPER_BUTTON_IMAGE = os.path.abspath('./images/paper.png')
    SCISSOR_BUTTON_IMAGE = os.path.abspath('./images/scissor.png')
    MAX_SCORE = 1
    RPS_BUTTON_SIZE = (100, 100)
    ROCK_BUTTON_POSITION = (100, 500)
    PAPER_BUTTON_POSITION = (500, 500)
    SCISSOR_BUTTON_POSITION = (300, 500)
    ROCK_BUTTON_HIGHLIGHTED_COLOR = (0,255, 255)
    SCISSOR_BUTTON_HIGHLIGHTED_COLOR = (255, 255, 0)
    PAPER_BUTTON_HIGHLIGHTED_COLOR = (255, 0, 0)
    PLAY_AGAIN_TEXT_POSITION = (230, 650)
    PLAY_AGAIN_TEXT_COLOR = (255, 255, 255)
    PLAY_AGAIN_TEXT = 'PRESS ANY KEY TO PLAY AGAIN'
    PLAY_AGAIN_TEXT_SIZE = 20
    PLAY_AGAIN_TEXT_NAME = 'comicsans'
    #
    LOCKED_IN_TEXT_POSITION = (480,400)
    LOCKED_IN_TEXT_COLOR = (200, 1, 1)
    LOCKED_IN_TEXT_SIZE = 30
    LOCKED_IN_TEXT_FONT = 'comicsans'
    LOCKED_IN_TEXT_LABEL = 'LOCKED IN'
    #
    PLAY_TEXT_POSITION = (100,400)
    PLAY_TEXT_COLOR = (255, 255, 255)
    PLAY_TEXT_SIZE = 30
    PLAY_TEXT_FONT = 'comicsans'
    PLAY_TEXT_LABLE = 'PLAY'
    #
    OPPONENT_MOVE_TEXT_POSITION = (490, 400)
    OPPONENT_MOVE_TEXT_COLOR = (0, 0, 0)
    OPPONENT_MOVE_TEXT_SIZE = 30
    OPPONENT_MOVE_TEXT_FONT = 'comicsans'
    #
    OPPONENT_WAITING_TEXT_POSITION = (490,400)
    OPPONENT_WAITING_TEXT_COLOR = (250, 250, 250)
    OPPONENT_WAITING_TEXT_SIZE = 30
    OPPONENT_WAITING_TEXT_FONT = 'comicsans'
    OPPONENT_WAITING_TEXT_LABEL = 'WAITING'
    #
    MOVE_TEXT_POSITION = (100,400)
    MOVE_TEXT_COLOR = (7, 42, 108)
    MOVE_TEXT_SIZE = 30
    MOVE_TEXT_FONT = 'comicsans'
    #
    
    SCORE_TEXT_POSITION = (80, 100)
    SCORE_TEXT_COLOR = (20, 20, 20)
    SCORE_TEXT_SIZE = 30
    SCORE_TEXT_FONT = 'comicsans'

    #
    OPPONENT_SCORE_TEXT_POSITION = (470, 100)
    OPPONENT_SCORE_TEXT_COLOR = (20,20, 20)
    OPPONENT_SCORE_TEXT_SIZE = 30
    OPPONENT_SCORE_TEXT_FONT = 'comicsans'

    #
    WIN_OR_LOSE_TEXT_POSITION = (200, 200)
    WIN_OR_LOSE_TEXT_SIZE = 60
    WIN_OR_LOST_TEXT_FONT = 'comicsans'
    WIN_TEXT_LABLE = 'YOU WON!'
    LOST_TEXT_LABLE = 'YOU LOST!'
    TIE_TEXT_LABLE = 'TIE GAME!'
    

    WIN_COLOR = (5, 102, 8)
    LOSE_COLOR = (200, 1, 1)
    TIE_COLOR = (255, 255, 255)
    GAME_SOUND = os.path.abspath('./audio/game-sound.ogg')

   